name: Deploy

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    name: Build
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          status: pending
          sha: ${{ github.event.workflow_run.head_sha }}
          context: Build

      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          status: ${{ job.status }}
          sha: ${{ github.event.workflow_run.head_sha }}
          context: Build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pages: write
      statuses: write
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          status: pending
          sha: ${{ github.event.workflow_run.head_sha }}
          context: Deploy

      - name: Download artifact
        uses: actions/download-artifact@v6
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always()
        with:
          status: ${{ job.status }}
          sha: ${{ github.event.workflow_run.head_sha }}
          context: Deploy
